// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKvbpwJgzqOSvDAxC6wlA73ATUXB9xKt0',
    appId: '1:1061261091920:web:c305e63cf1858dad845d55',
    messagingSenderId: '1061261091920',
    projectId: 'note-vole',
    authDomain: 'note-vole.firebaseapp.com',
    storageBucket: 'note-vole.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYHK-6Vf7zx7D2t6iWoUoK4LcUi1dhOYk',
    appId: '1:1061261091920:android:b6ec87e0ceb2ef90845d55',
    messagingSenderId: '1061261091920',
    projectId: 'note-vole',
    storageBucket: 'note-vole.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ATvWaNBXUcAko9QTYP8cevOYPfhe9_A',
    appId: '1:1061261091920:ios:6773bdb25457dbe8845d55',
    messagingSenderId: '1061261091920',
    projectId: 'note-vole',
    storageBucket: 'note-vole.appspot.com',
    iosBundleId: 'com.example.noteVole',
  );

}